### PR TITLE
Add Dutch card translation

### PR DESCRIPTION
**Pull request by jcassee**
This pull request does not translate the configuration strings.

### CODE REVIEW

**Comment by bruxy70** [comment]
Thanks! I suppose lots of HA users are from the Netherlands, Dutch was missing :).

**Comment by bruxy70** [comment]
@amaximus, would you like to add Dutch translation to your custom card? Thanks!

**Comment by jcassee** [comment]
Thanks, @bruxy70, that was quick!

**Comment by amaximus** [comment]
@bruxy70 , thanks for the heads-up. Added Spanish and Dutch translations to the card.

**Pull request merged**
