### PR TITLE
Set start time as expire_after if exists

### PR DESCRIPTION
**Pull request by jugla**
This pull request as a proposal of issue #268

### CODE REVIEW

**Comment by bruxy70** [comment]
The expire after is already mapped to the end time. It does not make sense to map it to the start time. When the collection expires, the event ends, not starts.

**Comment by jugla** [comment]
The issue is the information shown on calendar.
If end time is set, then start time as given in current source is set to midnight.
The idea was to improve this feature

**Comment by bruxy70** [comment]
This is correct, you know that the collection will happen sometimes before the start of the day and the expiration day.
There is no parameter to configure start time - there is IMHO already too many configuration options, and I do not see what would be the use of that anyhow. For the expiration time, that is different - after that time it will assume the collection is completed and it will show the next date. But for the start date, there would be no difference.
And I think I have tried to set the start time and end time the same, and there were some issues with that - can't recall exactly. DId you test that?

**Comment by jugla** [comment]
Hereafter the snapshot. I didn't change the behaviour of internal start and end time.
From my point of view, I'd just changed the event in calendar.
Normally, the expiration time shall not changed.
image

The point is that on my cellular phone the screen allow to display only the start date --> as a consequence, everything is set to zero (i.e. midnight)

**Comment by jugla** [comment]
Thanks !

**Pull request merged**
