### PR TITLE
Move collection day to next day if holiday in week

### PR DESCRIPTION
**Pull request by hasenbolle**
My garbage collection company skips the regular garabage collection day if there is a holiday in the same week. With this change the component will move the garbage collection the to the following day.

### CODE REVIEW

**Comment by bruxy70** [comment]
Thank you

**Comment by bruxy70** [comment]
@chriss158 , I am refactoring the code, can you please describe how this holiday in week is supposed to work. I never understood it properly. From the description it does not make sense to me.
The way I read it, if the collection is scheduled for Wednesday, and there is a holiday in the week (let's say on Tuesday), it will move the collection to the following data (to Thursday). Is that how it works? What if the holiday is on Thursday. Will it still move the collection to that day?

**Comment by chriss158** [comment]
Yes exactly. Thats how it should work. 

> What if the holiday is on Thursday. Will it still move the collection to that day?
No then the collection day should not be moved.
Initially the collection day was moved also if the holiday is after the collection day, but this was a bug, which was fixed here:
https://github.com/bruxy70/Garbage-Collection/commit/937d4a72b2d4ea2b0b8afa267f68c8c9043df29c

**Comment by bruxy70** [comment]
Thanks. The code had changed a lot since that, there were lots of requests, it became quite complicated. Can you please check 3.12-beta if that still works as intended?

So the purpose of this is, that they take the day off, and then shift all collections for one day. So their Tuesday shift moves to Wednesday, Wednesday to Thursday, Thursday to Friday, and Friday to Saturday. Is that how it works?

**Comment by chriss158** [comment]
> Thanks. The code had changed a lot since that, there were lots of requests, it became quite complicated. Can you please check 3.12-beta if that still works as intended?

Yes still working 👍 

> So the purpose of this is, that they take the day off, and then shift all collections for one day. So their Tuesday shift moves to Wednesday, Wednesday to Thursday, Thursday to Friday, and Friday to Saturday. Is that how it works?

Yes. 
Another example:
Collection day: Thursday
Holiday: Monday

Because Monday is a holiday and it is before the normal collection day (Thursday), the normal collection day (Thursday) is moved 1 day (Friday).

**Pull request merged**
